version: "3.4"

services:
  db:
    hostname: db
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  server:
    hostname: server
    build:
      dockerfile: Dockerfile
      context: server
    depends_on:
      - db

  client:
    hostname: client
    build:
      dockerfile: Dockerfile
      context: client
    depends_on:
      - server

  nginx:
    hostname: nginx
    image: nginx
    volumes:
      - ./nginx/app.conf:/etc/nginx/conf.d/app.conf
    ports:
      - "8000:8000"
    depends_on:
      - server
      - client

