version: "3.4"

services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    hostname: api

  nginx:
    image: nginx
    hostname: nginx
    ports:
      - "8000:8000"
    depends_on:
      - api